samples:
  GPSC15: seqs/SP/GPSC15_reference.fasta
  GPSC17: seqs/SP/GPSC17_reference.fasta
  GPSC22: seqs/SP/GPSC22_reference.fasta
  GPSC25: seqs/SP/GPSC25_reference.fasta
  GPSC26: seqs/SP/GPSC26_reference.fasta
  GPSC32: seqs/SP/GPSC32_reference.fasta
  GPSC34: seqs/SP/GPSC34_reference.fasta
  GPSC37: seqs/SP/GPSC37_reference.fasta
  GPSC3: seqs/SP/GPSC3_reference.fasta
  GPSC4: seqs/SP/GPSC4_reference.fasta
  GPSC5: seqs/SP/GPSC5_reference.fasta
  GPSC8: seqs/SP/GPSC8_reference.fasta
  JYGP01: seqs/SP/JYGP01.fasta
  NC_017592: seqs/SP/NC_017592.fasta

target: "Streptococcus"
bed: "SP.scheme.primer.bed"