file_paths:
  - "results/prokka_roary/roary/accessory.header.embl"
  - "results/prokka_roary/roary/accessory_binary_genes.fa"
  - "results/prokka_roary/roary/accessory_binary_genes.fa.newick"
  - "results/prokka_roary/roary/accessory_graph.dot"
  - "results/prokka_roary/roary/accessory.tab"
  - "results/prokka_roary/roary/blast_identity_frequency.Rtab"
  - "results/prokka_roary/roary/clustered_proteins"
  - "results/prokka_roary/roary/core_accessory.header.embl"
  - "results/prokka_roary/roary/core_accessory.tab"
  - "results/prokka_roary/roary/core_accessory_graph.dot"
  - "results/prokka_roary/roary/core_alignment_header.embl"
  - "results/prokka_roary/roary/gene_presence_absence.Rtab"
  - "results/prokka_roary/roary/number_of_conserved_genes.Rtab"
  - "results/prokka_roary/roary/number_of_genes_in_pan_genome.Rtab"
  - "results/prokka_roary/roary/number_of_new_genes.Rtab"
  - "results/prokka_roary/roary/number_of_unique_genes.Rtab"
  - "results/prokka_roary/roary/pan_genome_reference.fa"
  - "results/prokka_roary/roary/summary_statistics.txt"
  - "results/prokka_roary/roary/core_gene_alignment.aln"
  - "results/prokka_roary/roary/gene_presence_absence.csv"
  - "results/prokka_roary/roary/tree.newick"
  #- "pangenome_frequency.png", 
  #- "pangenome_matrix.png",
  #- "pangenome_pie.png"