samples:
  GPSC15: seqs/SP_reps/GPSC15_reference.fasta
  GPSC17:  seqs/SP_reps/GPSC17_reference.fasta
  GPSC22:  seqs/SP_reps/GPSC22_reference.fasta
  GPSC25:  seqs/SP_reps/GPSC25_reference.fasta
  GPSC26:  seqs/SP_reps/GPSC26_reference.fasta
  GPSC32:  seqs/SP_reps/GPSC32_reference.fasta
  GPSC34:  seqs/SP_reps/GPSC34_reference.fasta
  GPSC37:  seqs/SP_reps/GPSC37_reference.fasta
  GPSC3:  seqs/SP_reps/GPSC3_reference.fasta
  GPSC4:  seqs/SP_reps/GPSC4_reference.fasta
  GPSC5:  seqs/SP_reps/GPSC5_reference.fasta
  GPSC8:  seqs/SP_reps/GPSC8_reference.fasta
  JYGP01:  seqs/SP_reps/JYGP01.fasta
  NC_017592: seqs/SP_reps/NC_017592.fasta

file_paths:
  - results/SP/roary_reps/roary/accessory.header.embl
  - results/SP/roary_reps/roary/accessory_binary_genes.fa
  - results/SP/roary_reps/roary/accessory_binary_genes.fa.newick
  - results/SP/roary_reps/roary/accessory_graph.dot
  - results/SP/roary_reps/roary/accessory.tab
  - results/SP/roary_reps/roary/blast_identity_frequency.Rtab
  - results/SP/roary_reps/roary/clustered_proteins
  - results/SP/roary_reps/roary/core_accessory.header.embl
  - results/SP/roary_reps/roary/core_accessory.tab
  - results/SP/roary_reps/roary/core_accessory_graph.dot
  - results/SP/roary_reps/roary/core_alignment_header.embl
  - results/SP/roary_reps/roary/gene_presence_absence.Rtab
  - results/SP/roary_reps/roary/number_of_conserved_genes.Rtab
  - results/SP/roary_reps/roary/number_of_genes_in_pan_genome.Rtab
  - results/SP/roary_reps/roary/number_of_new_genes.Rtab
  - results/SP/roary_reps/roary/number_of_unique_genes.Rtab
  - results/SP/roary_reps/roary/pan_genome_reference.fa
  - results/SP/roary_reps/roary/summary_statistics.txt
  - results/SP/roary_reps/roary/core_gene_alignment.aln
  - results/SP/roary_reps/roary/gene_presence_absence.csv
  - results/SP/roary_reps/roary/tree.newick
  - results/SP/roary_reps/fastani/fastani.out
  - results/SP/roary_reps/mash/mash.txt
