base_path: "seqs/SP/"
genus: "Streptococcus"
ref: "NC_017592.fasta"
samples:
  - "JYGP01.fasta"
  - "NC_017592.fasta"
  - "GPSC10_reference.fasta"
  - "GPSC11_reference.fasta"
  - "GPSC13_reference.fasta"
  - "GPSC14_reference.fasta"
  - "GPSC15_reference.fasta"
  - "GPSC16_reference.fasta"
  - "GPSC17_reference.fasta"
  - "GPSC18_reference.fasta"
  - "GPSC19_reference.fasta"
  - "GPSC1_reference.fasta"
  - "GPSC21_reference.fasta"
  - "GPSC22_reference.fasta"
  - "GPSC23_reference.fasta"
  - "GPSC25_reference.fasta"
  - "GPSC26_reference.fasta"
  - "GPSC27_reference.fasta"
  - "GPSC2_reference.fasta"
  - "GPSC30_reference.fasta"
  - "GPSC31_reference.fasta"
  - "GPSC32_reference.fasta"
  - "GPSC33_reference.fasta"
  - "GPSC34_reference.fasta"
  - "GPSC37_reference.fasta"
  - "GPSC3_reference.fasta"
  - "GPSC40_reference.fasta"
  - "GPSC43_reference.fasta"
  - "GPSC47_reference.fasta"
  - "GPSC4_reference.fasta"
  - "GPSC5_reference.fasta"
  - "GPSC6_reference.fasta"
  - "GPSC7_reference.fasta"
  - "GPSC8_reference.fasta"
  - "GPSC9_reference.fasta"