samples:
  ERR133985: seqs/TB_reps/ERR133985.fa
  ERR181435: seqs/TB_reps/ERR181435.fa
  ERR229952: seqs/TB_reps/ERR229952.fa 
  ERR234202: seqs/TB_reps/ERR234202.fa
  H37Rv: seqs/TB_reps/H37Rv.fa 
  NC_019950: seqs/TB_reps/NC_019950.fa  
  SRR1019139: seqs/TB_reps/SRR1019139.fa 
  SRR1163294: seqs/TB_reps/SRR1163294.fa 
  SRR1173445: seqs/TB_reps/SRR1173445.fa 
  SRR1173640: seqs/TB_reps/SRR1173640.fa
  SRR1175079: seqs/TB_reps/SRR1175079.fa 
  SRR1180462: seqs/TB_reps/SRR1180462.fa  
  SRR671749: seqs/TB_reps/SRR671749.fa 
  SRR998654: seqs/TB_reps/SRR998654.fa

file_paths:
  - results/TB/roary_reps/roary/accessory.header.embl
  - results/TB/roary_reps/roary/accessory_binary_genes.fa
  - results/TB/roary_reps/roary/accessory_binary_genes.fa.newick
  - results/TB/roary_reps/roary/accessory_graph.dot
  - results/TB/roary_reps/roary/accessory.tab
  - results/TB/roary_reps/roary/blast_identity_frequency.Rtab
  - results/TB/roary_reps/roary/clustered_proteins
  - results/TB/roary_reps/roary/core_accessory.header.embl
  - results/TB/roary_reps/roary/core_accessory.tab
  - results/TB/roary_reps/roary/core_accessory_graph.dot
  - results/TB/roary_reps/roary/core_alignment_header.embl
  - results/TB/roary_reps/roary/gene_presence_absence.Rtab
  - results/TB/roary_reps/roary/number_of_conserved_genes.Rtab
  - results/TB/roary_reps/roary/number_of_genes_in_pan_genome.Rtab
  - results/TB/roary_reps/roary/number_of_new_genes.Rtab
  - results/TB/roary_reps/roary/number_of_unique_genes.Rtab
  - results/TB/roary_reps/roary/pan_genome_reference.fa
  - results/TB/roary_reps/roary/summary_statistics.txt
  - results/TB/roary_reps/roary/core_gene_alignment.aln
  - results/TB/roary_reps/roary/gene_presence_absence.csv
  - results/TB/roary_reps/roary/tree.newick
  - results/TB/roary_reps/fastani/fastani.out
  - expand("results/TB/roary_reps/mash/dummy_{sample}.txt", sample=config["samples"])